export * from "./percentOperation"
export * from "./pressNumber"
export * from "./getButtonBackground"
export * from "./addOperation"
export * from "./sendResult"
export * from "./decimalNumber"
export * from "./alterOperation"
export * from "./resetScreen"
